### ISSUE TITLE
Sylius 1.4

### ISSUE THREAD

**Issue by d4rqu** [promsters/sylius-dotpay-real#2]
Czy jest szansa na aktualizacje dla syliusa 1.4?

**Comment by promsters** [comment]
Zaktualizuję jutro :)

wt., 12 mar 2019, 21:13 użytkownik d4rqu <notifications@github.com> napisał:

**Comment by d4rqu** [comment]
I jak udalo sie? :)

**Comment by promsters** [comment]
Zaktualizowane.
